framework:
  - terraform

directory:
  - aws/
  - gcp/

compact: true
quiet: true

# Skip checks for intentional design choices.
# Each skip includes a rationale — these are reviewed during security audits.
skip-check:

  # --- Encryption: AWS-managed encryption is used by default. CMK/CSEK is optional. ---

  # S3 bucket keys (single KMS key per bucket) rather than per-object KMS ARNs.
  - CKV_AWS_145  # S3 Bucket KMS key ARN

  # DynamoDB uses AWS-managed encryption. CMK is available but adds cost/complexity
  # for a metadata store that contains no customer data.
  - CKV_AWS_119  # DynamoDB Tables encrypted using KMS CMK

  # CloudWatch logs use AWS-managed encryption. KMS CMK for log groups is optional.
  - CKV_AWS_158  # CloudWatch Log Group encrypted by KMS

  # CloudTrail uses SSE-S3 on the audit bucket. KMS CMK is optional and adds key
  # management overhead for audit logs that are already access-controlled.
  - CKV_AWS_35   # CloudTrail logs encrypted at rest using KMS CMKs

  # BigQuery uses Google-managed encryption by default. CSEK adds key management
  # burden; CMEK is supported via enable_cmek on the storage module.
  - CKV_GCP_81   # BigQuery Datasets encrypted with CSEK

  # --- Logging: alternative mechanisms are in place ---

  # S3 access logging is opt-in via enable_cloudtrail. CloudTrail data-event
  # logging provides equivalent or better audit coverage.
  - CKV_AWS_18   # S3 bucket access logging enabled

  # ALB access logs require a pre-existing S3 bucket. CloudWatch Container Insights
  # provides equivalent monitoring for Nessie.
  - CKV_AWS_91   # ALB access logging enabled

  # GCS bucket logging is handled by the Cloud Audit Log sink, not bucket-level
  # access logs. The sink exports to a dedicated audit bucket.
  - CKV_GCP_62   # Bucket should log access

  # CloudTrail is scoped to lakehouse S3 data events, not an org-wide trail.
  # Multi-region is not needed for a single-bucket data event trail.
  - CKV_AWS_67   # CloudTrail enabled in all Regions

  # CloudTrail → CloudWatch integration is optional. Audit logs are stored in S3
  # with a 7-year lifecycle; CloudWatch is used separately for ECS monitoring.
  - CKV2_AWS_10  # CloudTrail integrated with CloudWatch Logs

  # SNS topic on CloudTrail is optional. Alerting is handled via Dagster sensors
  # and CloudWatch alarms, not CloudTrail SNS notifications.
  - CKV_AWS_252  # CloudTrail defines an SNS Topic

  # VPC flow logging is opt-in. Not all deployments need VPC-level packet logging,
  # and it adds cost. Enable via a separate aws_flow_log resource when required.
  - CKV2_AWS_11  # VPC flow logging enabled

  # S3 event notifications are optional. Not needed for the lakehouse or audit buckets
  # — monitoring is handled via CloudTrail and CloudWatch.
  - CKV2_AWS_62  # S3 buckets should have event notifications enabled

  # GCP bucket lock on log sink retention is optional. The audit bucket has a
  # lifecycle policy; bucket lock prevents policy changes but also prevents cleanup.
  - CKV2_GCP_4   # Retention policies on log buckets configured using Bucket Lock

  # --- Networking: intentional design for the Nessie ECS architecture ---

  # NAT gateway is created in public subnets by design — it needs a route to
  # the internet gateway to provide outbound connectivity for private subnets.
  - CKV2_AWS_19  # All EIP addresses allocated to a VPC are attached

  # Public subnets host the ALB and NAT gateway. ECS tasks run in private subnets.
  # map_public_ip_on_launch is default (false) but Checkov flags the subnet itself.
  - CKV_AWS_130  # VPC subnets do not assign public IP by default

  # ECS containers and ALB need unrestricted egress for pulling images, health
  # checks, and reaching AWS APIs. Ingress is restricted by nessie_allowed_cidrs.
  - CKV_AWS_382  # No security groups allow egress 0.0.0.0:0 to port -1

  # Security group descriptions are cosmetic. Groups are named and tagged; adding
  # description fields is a low-value change.
  - CKV_AWS_23   # Every security group and rule has a description

  # The default VPC security group is not used by any resource. All resources use
  # dedicated security groups (alb, nessie).
  - CKV2_AWS_12  # Default security group restricts all traffic

  # --- ALB/HTTPS: TLS is opt-in via certificate_arn variable ---

  # HTTPS listener is created when certificate_arn is set. Without a cert, the ALB
  # serves HTTP (quickstart/dev). Production deployments set certificate_arn.
  - CKV_AWS_2    # ALB protocol is HTTPS
  - CKV_AWS_103  # Load balancer using at least TLS 1.2
  - CKV2_AWS_20  # ALB redirects HTTP requests into HTTPS
  - CKV_AWS_131  # ALB drops HTTP headers

  # ALB → ECS target group uses HTTP. TLS terminates at the ALB; internal traffic
  # stays within the VPC on a private subnet.
  - CKV_AWS_378  # Load Balancer doesn't use HTTP protocol

  # ALB deletion protection is off by default for dev/quickstart. Production
  # deployments should set enable_deletion_protection = true in tfvars.
  - CKV_AWS_150  # Load Balancer has deletion protection enabled

  # --- S3: optional features that depend on deployment requirements ---

  # Cross-region replication requires a destination bucket in another region.
  # Enable when DR requirements mandate it; not needed for all deployments.
  - CKV_AWS_144  # S3 bucket has cross-region replication enabled

  # Checkov doesn't associate the lifecycle configuration resource with the bucket
  # when they're defined as separate resources (aws_s3_bucket_lifecycle_configuration).
  - CKV2_AWS_61  # S3 bucket has a lifecycle configuration
  - CKV_AWS_300  # S3 lifecycle sets period for aborting failed uploads

  # Checkov doesn't associate the public access block and versioning resources
  # with the audit bucket when defined as separate resources.
  - CKV2_AWS_6   # S3 bucket has a Public Access block
  - CKV_AWS_21   # S3 bucket versioning enabled

  # --- GCP: public access prevention ---

  # GCS buckets use uniform bucket-level access. Public access prevention is
  # controlled via IAM; the buckets have no allUsers/allAuthenticatedUsers bindings.
  - CKV_GCP_114  # Public access prevention enforced on Cloud Storage bucket
